Theo dev
Alabhya/Access-Entree pull request #79
Opened 2022-07-06 04:14 UTC by Harlock9651

Implemented and documented the 'Stay in Bounds' functionality in Area 3.

2022-07-09 14:58 UTC, lcundiff requested changes

2022-07-09 14:58 UTC, lcundiff commented on Assets/Sandbox/Theoden/Code/StayInBounds.cs
> +	[SerializeField] private Vector3 maxVals; //The larges bounds of the level boundary
```suggestion
	[SerializeField] private Vector3 maxVals; //The largest bounds of the level boundary
```

2022-07-09 14:58 UTC, lcundiff commented on Assets/Sandbox/Theoden/Code/StayInBounds.cs
> +    // Update is called once per frame
```suggestion
```

2022-07-09 14:58 UTC, lcundiff commented on Assets/Sandbox/Theoden/Code/StayInBounds.cs
> +		if(minVals.x > player.transform.position.x || maxVals.x < player.transform.position.x || minVals.y > player.transform.position.y || maxVals.y < player.transform.position.y || minVals.z > player.tra
```suggestion
	//If not, move the player back to the respawn point.
	if(minVals.x > player.transform.position.x || maxVals.x < player.transform.position.x || minVals.y > player.transform.position.y || maxVals.y < player.transform.position.y || minVals.z > player.transform.position.z || maxVals.z < player.transform.position.z)
```

2022-07-09 14:58 UTC, lcundiff commented on Assets/Sandbox/Theoden/Code/Scene Transitions/SceneTransition.cs
> +		}
So my suggestion here would be to move this into your TransitionTrigger class and "yield return StartCoroutine" there in order to wait for this function to finish and then run your two lines of code there. 

The benefit of this would be separating your two concerns: moving player and handling the transition. It also removes a conditional and parameter, making the code slightly more simple.

2022-07-09 14:58 UTC, lcundiff commented on Assets/Sandbox/Theoden/Code/StayInBounds.cs
> +		Debug.Log("Whoopsie doodle: Player out of bounds");
Nice haha

2022-07-09 20:51 UTC, Harlock9651 commented on Assets/Sandbox/Theoden/Code/StayInBounds.cs
> +    // Update is called once per frame
Any reason I should take this out?

2022-07-09 20:53 UTC, Harlock9651 commented on Assets/Sandbox/Theoden/Code/StayInBounds.cs
> +		if(minVals.x > player.transform.position.x || maxVals.x < player.transform.position.x || minVals.y > player.transform.position.y || maxVals.y < player.transform.position.y || minVals.z > player.tra
Not really sure what the issue is here either. Like a tab or something?

2022-07-09 21:02 UTC, Harlock9651 commented on Assets/Sandbox/Theoden/Code/StayInBounds.cs
> +		Debug.Log("Whoopsie doodle: Player out of bounds");
See, Error sounds way too scary for what's happening.

2022-07-17 19:59 UTC, lcundiff approved these changes

2022-07-24 14:16 UTC, merged