Bridge Integrated and working perfectly....
Alabhya/Access-Entree pull request #97
Opened 2022-10-01 16:27 UTC by iAmUmar

2022-10-05 11:11 UTC, lcundiff requested changes

2022-10-05 11:11 UTC, lcundiff commented on Assets/Scripts/BuildableObject.cs
> +            // playerInventory.ReduceItemAmount(removeItemObj);
```suggestion
```

2022-10-05 11:11 UTC, lcundiff commented on Assets/Scripts/BuildableObject.cs
> +    [SerializeField] InventoryItem playerInventory;
```suggestion
```
I dont think this is being used?

2022-10-05 11:11 UTC, lcundiff commented on Assets/Scripts/BuildableObject.cs
> -
Good job simplifying code!

2022-10-05 11:11 UTC, lcundiff commented on Assets/Scripts/BuildableObject.cs
> +        var values = requiredInventory.Select(v => v.Value).ToArray();
can we use a different name instead of "keys" and "values"?

2022-10-05 11:11 UTC, lcundiff commented on Assets/Scripts/Player/PlayerInteract.cs
> +    private bool isLooking = false;
What will this be used for?

2022-10-06 10:51 UTC, iAmUmar commented
Done reviewing your comments Logan.. Lookingforrward to hear from you.

2022-10-09 09:37 UTC, iAmUmar commented on Assets/Scripts/Player/PlayerInteract.cs
> +    private bool isLooking = false;
Removed this. Was looking to delete iterative check with boolean but couldn't able to implement that thing right now.

2022-10-09 09:37 UTC, iAmUmar commented on Assets/Scripts/BuildableObject.cs
> +    [SerializeField] InventoryItem playerInventory;
Yup.. Removed from code

2022-10-10 03:48 UTC, Alabhya approved these changes

2022-10-12 03:28 UTC, lcundiff approved these changes

2022-10-12 13:52 UTC, merged